# Generated by Django 4.2.21 on 2025-09-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_images/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='store_name',
            field=models.CharField(max_length=255),
        ),
    ]
