# Generated by Django 4.2.21 on 2025-09-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_wishlist_products_remove_wishlist_user_and_more'),
        ('home', '0005_add_review_system'),
    ]

    operations = [
    ]
