# Generated by Django 4.2.21 on 2025-09-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20250928_1730'),
        ('home', '0007_fix_migration_conflict'),
    ]

    operations = [
    ]
